### ISSUE TITLE
Version 1.0 release to do list

### ISSUE THREAD

**Issue by harry093** [GeoscienceAustralia/GeodePy#132]
Before releasing GeodePy v1.0 the following needs to  be done:

- [ ] Standardise names of Transformation objects, etc. (#129)
- [ ] Define reverse transformations (#127)
- [ ] Set up GitHub Actions to replace Travis (#130)
- [ ] Define style guide (#128)
- [ ] Standardise doc strings
- [ ] Create a Users' Guide (from doc strings or see Read the Docs) (#131)
- [ ] Full test coverage
